import { StyleSheet } from 'react-native';
import COLORS from '../../Base/constants';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F4F7FC',
        position: 'relative',

    },
    header: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        zIndex: 50,
        flexDirection: 'row-reverse',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 24,
        paddingBottom: 20,
        backgroundColor: '#F8F9FB', // Match screen background for seamless glass effect if needed
    },
    dateHeaderContainer: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 24, // Position it slightly above the bottom of the header
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: -1,
    },
    topDateText: {
        fontFamily: 'Alexandria-Medium',
        fontSize: 12,
        color: '#94A3B8',
        letterSpacing: 0.3,
        textTransform: 'uppercase',
    },
    notificationContainer: {
        position: 'relative',
        padding: 8,
        backgroundColor: '#FFF',
        borderRadius: 14,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 2,
    },
    notificationBadge: {
        position: 'absolute',
        top: 4,
        right: 4,
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: '#FF5252',
        borderWidth: 1.5,
        borderColor: '#F8F9FB',
    },
    avatarContainer: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    avatar: {
        width: 45,
        height: 45,
        borderRadius: 22.5,
        backgroundColor: '#DDD',
    },
    sectionTitle: {
        fontFamily: 'Alexandria-Bold',
        fontSize: 24,
        color: '#000',
        textAlign: 'center',
        marginBottom: 32,
        marginTop: 16,
    },
    upcomingHeader: {
        fontFamily: 'Alexandria-Bold',
        fontSize: 20,
        color: COLORS.PrimarySlate,
        marginBottom: 24,
        marginTop: 8,
        textAlign: 'right',
        textShadowColor: 'rgba(0, 0, 0, 0.3)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 1,
    },
    upcomingTitle: {
        textAlign: 'right',
        marginBottom: 16,
        marginTop: 32,
    },
    currentBookingSection: {
        alignItems: 'center',
        paddingHorizontal: 24,
        marginBottom: 20,
    },
    hexagonContainer: {
        width: 300,
        height: 330,
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative',
        overflow: 'hidden',
        backgroundColor: '#F4F7FC',
    },
    hexagonImageBackground: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
        position: 'absolute',

    },
    hexagonOverlay: {
        backgroundColor: 'rgba(0,0,0,0.2)',
    },
    hexagonSvg: {
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 10,
        },
        shadowOpacity: 0.4,
        shadowRadius: 10,
        overflow: 'hidden',
        // Elevation implies native shadow which doesn't work well on Svg directly without View, 
        // but the Svg is inside a View
    },
    hexagonContent: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
    },
    overlayTitle: {
        fontFamily: 'Alexandria-Bold',
        fontSize: 22,
        color: '#FFF',
        textAlign: 'center',
        textShadowColor: 'rgba(0, 0, 0, 0.5)',
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 4,
    },
    overlaySubtitle: {
        fontFamily: 'Alexandria-Regular',
        fontSize: 14,
        color: '#DDD',
        textAlign: 'center',
        textShadowColor: 'rgba(0, 0, 0, 0.4)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 2,
    },
    hallBadge: {
        position: 'absolute',
        bottom: 15,
        alignSelf: 'center',
        width: 40,
        height: 40,
        borderRadius: 25,
        backgroundColor: '#EAEAEA',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 4,
        borderColor: '#3D3D3D',
        zIndex: 10,
    },
    hallBadgeText: {
        fontFamily: 'Alexandria-Bold',
        fontSize: 18,
        color: '#3D3D3D',
    },
    detailsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        paddingHorizontal: 48,
        marginTop: -20,

    },
    detailItem: {
        alignItems: 'center',

    },
    detailLabel: {
        fontFamily: 'Alexandria-Regular',
        fontSize: 14,
        color: '#000000',
        opacity: 0.5,
        marginTop: 6,
        lineHeight: 18,
    },
    detailValue: {
        fontFamily: 'Alexandria-Regular',
        fontSize: 18,
        color: '#000',
    },
    listContent: {
        direction: 'ltr',
        paddingHorizontal: 24,
        paddingTop: 80,
        paddingBottom: 100,
    },
    list: {
        flex: 1,
    },
    bookingCard: {
        flexDirection: 'row',
        direction: 'ltr',
        backgroundColor: '#FFF',
        borderRadius: 16,
        padding: 12,
        marginBottom: 16,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    bookingImage: {
        width: 80,
        height: 80,
        borderRadius: 12,
        backgroundColor: '#F0F0F0',
    },
    bookingInfo: {
        flex: 1,
        marginRight: 16,
        alignItems: 'flex-end',
    },
    bookingTitle: {
        fontFamily: 'Alexandria-Bold',
        fontSize: 16,
        color: COLORS.PrimarySlate,
        marginBottom: 4,
        textShadowColor: 'rgba(0, 0, 0, 0.2)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 1,
    },
    bookingRow: {
        flexDirection: 'row-reverse',
        alignItems: 'center',
        marginBottom: 2,
    },
    bookingText: {
        fontFamily: 'Alexandria-Regular',
        fontSize: 12,
        color: '#666',
        marginLeft: 4,
        textShadowColor: 'rgba(0, 0, 0, 0.15)',
        textShadowOffset: { width: 0, height: 0.5 },
        textShadowRadius: 0.5,
    },
    bookingLabel: {
        fontFamily: 'Alexandria-Light',
        fontSize: 10,
        color: '#999',
        textShadowColor: 'rgba(0, 0, 0, 0.15)',
        textShadowOffset: { width: 0, height: 0.5 },
        textShadowRadius: 0.5,
    },
});
