import { StyleSheet } from 'react-native';
import COLORS from '../../Base/constants';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8F9FB',
        position: 'relative',

    },
    header: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        zIndex: 50,
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: 24,
        paddingBottom: 16,
    },
    notificationContainer: {
        position: 'relative',
        padding: 4,
    },
    notificationBadge: {
        position: 'absolute',
        top: 4,
        right: 4,
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: '#FF5252',
        borderWidth: 1.5,
        borderColor: '#F8F9FB',
    },
    avatarContainer: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    avatar: {
        width: 45,
        height: 45,
        borderRadius: 22.5,
        backgroundColor: '#DDD',
    },
    sectionTitle: {
        fontFamily: 'Alexandria-Light',
        fontSize: 28,
        color: COLORS.PrimarySlate,
        textAlign: 'center',
        marginBottom: 24,
        marginTop: 8,
    },
    upcomingHeader: {
        fontFamily: 'Alexandria-Regular',
        fontSize: 20,
        color: COLORS.PrimarySlate,
        marginBottom: 24,
        marginTop: 8,
        textAlign: 'right',
    },
    upcomingTitle: {
        textAlign: 'right',
        marginBottom: 16,
        marginTop: 32,
    },
    currentBookingSection: {
        alignItems: 'center',
        paddingHorizontal: 24,
        marginBottom: 20,
    },
    hexagonContainer: {
        width: 300,
        height: 330,
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative',
        overflow: 'hidden',
    },
    hexagonImageBackground: {
        transform: [{ scale: 0.4 }], // Adjusted scale for 330 height
        position: 'absolute',

        transformOrigin: 'center',
    },
    hexagonOverlay: {
        backgroundColor: 'rgba(0,0,0,0.2)',
    },
    hexagonSvg: {
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 10,
        },
        shadowOpacity: 0.4,
        shadowRadius: 10,
        overflow: 'hidden',
        // Elevation implies native shadow which doesn't work well on Svg directly without View, 
        // but the Svg is inside a View
    },
    hexagonContent: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
    },
    overlayTitle: {
        fontFamily: 'Alexandria-Bold',
        fontSize: 22,
        color: '#FFF',
        textAlign: 'center',
        marginBottom: 4,
    },
    overlaySubtitle: {
        fontFamily: 'Alexandria-Regular',
        fontSize: 14,
        color: '#DDD',
        textAlign: 'center',
    },
    hallBadge: {
        position: 'absolute',
        bottom: 15, // Adjusted for 330 height
        alignSelf: 'center',
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#FFF',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#333',
        zIndex: 10,
        elevation: 5,
        shadowColor: '#000',
    },
    hallBadgeText: {
        fontFamily: 'Alexandria-Bold',
        fontSize: 20,
        color: '#333',
    },
    detailsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        marginTop: 0,
        paddingHorizontal: 16,
    },
    detailItem: {
        alignItems: 'center',
    },
    detailLabel: {
        fontFamily: 'Alexandria-Light',
        fontSize: 12,
        color: '#666',
        marginTop: 4,
        marginBottom: 2,
    },
    detailValue: {
        fontFamily: 'Alexandria-Bold',
        fontSize: 14,
        color: '#000',
    },
    listContent: {
        direction: 'ltr',
        paddingHorizontal: 24,
        paddingTop: 80,
        paddingBottom: 100,
    },
    list: {
        flex: 1,
    },
    bookingCard: {
        flexDirection: 'row',
        backgroundColor: '#FFF',
        borderRadius: 16,
        padding: 12,
        marginBottom: 16,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    bookingImage: {
        width: 80,
        height: 80,
        borderRadius: 12,
        backgroundColor: '#F0F0F0',
    },
    bookingInfo: {
        flex: 1,
        marginRight: 16,
        alignItems: 'flex-end',
    },
    bookingTitle: {
        fontFamily: 'Alexandria-Bold',
        fontSize: 16,
        color: COLORS.PrimarySlate,
        marginBottom: 4,
    },
    bookingRow: {
        flexDirection: 'row-reverse',
        alignItems: 'center',
        marginBottom: 2,
    },
    bookingText: {
        fontFamily: 'Alexandria-Regular',
        fontSize: 12,
        color: '#666',
        marginLeft: 4,
    },
    bookingLabel: {
        fontFamily: 'Alexandria-Light',
        fontSize: 10,
        color: '#999',
    },
});
